name: SubGuard Monthly Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 25 * *"

jobs:
  run-subguard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run SubGuard
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python subguard.py
